---
# MinIO Service Configuration
minio_user: "minio-user"
minio_group: "minio-user"

# Cluster Configuration Syntax. e.g. http://IP-{start...end}/data{1...n}
minio_cluster_vol_string: "http://{{ minio_cluster_start_ip | default('172.16.138.20') }}{0...3}:9000/data{1...2}"
minio_root_user: "admin"

# Disk Configuration corresponding to Terraform-mounted vdb, vdc
minio_data_drives:
  - device: "/dev/vdb"
    mount_point: "/data1"
  - device: "/dev/vdc"
    mount_point: "/data2"
