---
common:
  ubuntu:
    packages:
      # System & Package Management Utilities
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - lsb-release
      - gpg
      - gnupg-agent
      - snapd

      # Downloading & Transfer Utilities
      - curl
      - wget

      # Development & Build Tools
      - build-essential
      - python3-pip

      # File, Text, & Data Utilities
      - vim
      - jq
      - tree
      - unzip

      # Monitoring & Network Tools
      - htop
      - net-tools
