---
- name: Restart redis-server
  ansible.builtin.systemd:
    name: redis-server
    state: restarted

- name: Restart redis-sentinel
  ansible.builtin.systemd:
    name: redis-sentinel
    state: restarted

- name: Restart Vault Agent
  listen: "Restart Vault Agent"
  ansible.builtin.systemd:
    name: vault-agent
    state: restarted
