---
- name: Restart MinIO
  ansible.builtin.systemd:
    name: minio
    state: restarted

- name: Restart Vault Agent
  ansible.builtin.systemd:
    name: vault-agent
    state: restarted
  listen: "Restart Vault Agent"
