---
- name: "Section B: Install Redis Server from Official Repository"
  block:
    - name: "Step B2. Create directory for apt keyrings"
      ansible.builtin.file:
        path: "{{ _redis_base_repo_data.gpg_keyring_path | dirname }}"
        state: directory
        mode: "0755"

    - name: "Step B3. Add Redis official GPG key"
      ansible.builtin.apt_key:
        url: "{{ _redis_base_repo_data.gpg_url }}"
        keyring: "{{ _redis_base_repo_data.gpg_keyring_path }}"
        state: present

    - name: "Step B4. Add Redis APT repository"
      ansible.builtin.apt_repository:
        repo: "{{ _redis_base_repo_string }}"
        state: present
        filename: "{{ _redis_base_repo_data.filename }}"

    - name: "Step B5. Install Redis server package"
      ansible.builtin.apt:
        name: "{{ redis_base.packages.apt }}"
        state: present
        update_cache: true

    - name: "Step B6. Stop and disable redis services for packer image building stage"
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop: "{{ redis_base.services_to_disable }}"
      ignore_errors: true
