---
# PostgreSQL Version
postgres_version: 18

# For other sources (Calico default for Microk8s, Kubeadm, etc.) to enforce mTLS
postgres_mtls_pod_subnet: "10.1.0.0/16"
# Note that postgres_mtls_node_subnet is injected from Terraform via inventory.

# Ports
postgres_port: 5432
patroni_restapi_port: 8008
