---
- name: Section A. Install Kubeadm and Bootstrap the Cluster
  ansible.builtin.include_tasks: A-install-kubeadm.yaml
# - name: Section B. Install Calico for Cluster Testing
#   ansible.builtin.include_tasks: B-install-calico.yaml
