---
- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Update CA Trust
  ansible.builtin.command:
    cmd: update-ca-certificates

- name: Restart Vault
  ansible.builtin.systemd:
    name: vault
    state: restarted
