---
- name: "Block A: Install Common Base Packages"
  become: true
  block:
    - name: "Step A1. Install Common Base Packages"
      ansible.builtin.apt:
        name: "{{ common.ubuntu.packages }}"
        state: present
        update_cache: true
      no_log: true
