---
# HAProxy Port Configuration, RW for Primary, RO for Replicas
haproxy_stats_port: 7000
haproxy_rw_port: 5000
haproxy_ro_port: 5001

# Backend Health Check Port (Patroni API)
patroni_api_port: 8008
postgres_port: 5432

# Keepalived Tuning
keepalived_router_id: "{{ service_identifier }}-postgres-lb"
keepalived_vrrp_id: 71
keepalived_advert_int: 1
